#requires -version 5.1
<#
.SYNOPSIS
    Regenerate cmake/xp-forbidden-imports.txt, the list of Win32 APIs that
    Windows XP does not have.

.DESCRIPTION
    The toolchain already knows the answer. mingw-w64 guards each declaration
    with the version that introduced it, so preprocessing the Windows headers
    twice -- once at _WIN32_WINNT=0x0501 and once at 0x0600 -- and keeping the
    names only the second run declares gives the set that arrived after XP.

    That is worth the trouble because a hand written list is wrong in both
    directions. It misses whatever nobody thought of, which is the whole point
    of having a gate; and it names things that only sound new, such as
    GetModuleHandleExW, which has been there since XP.

    CheckXPImports.cmake fails an XP-targeted build that imports one of these.

    The result is only as complete as the headers listed below, so a name
    declared in some header this does not reach is a gap in the list rather
    than a false alarm -- add the header if a DLL turns up that none of these
    covers.

.PARAMETER Compiler
    The 32 bit mingw-w64 C compiler to ask. Must be on PATH or an absolute
    path.

.EXAMPLE
    tools\win\gen-xp-forbidden-imports.ps1

.EXAMPLE
    tools\win\gen-xp-forbidden-imports.ps1 C:\msys64\mingw32\bin\i686-w64-mingw32-gcc.exe
#>
[CmdletBinding()]
param([string]$Compiler = 'i686-w64-mingw32-gcc')

$ErrorActionPreference = 'Stop'

# winsock2.h before windows.h, or it warns and declares the older sockets only.
$headers = @'
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <shlwapi.h>
#include <shlobj.h>
#include <commctrl.h>
#include <commdlg.h>
#include <uxtheme.h>
#include <setupapi.h>
#include <oleacc.h>
#include <mmsystem.h>
#include <imm.h>
#include <winspool.h>
#include <wincrypt.h>
#include <winternl.h>
'@

$banner = @'
# Win32 APIs that Windows XP does not have.
#
# Generated by tools/win/gen-xp-forbidden-imports.ps1 -- do not hand edit. It
# preprocesses the Windows headers twice, at _WIN32_WINNT=0x0501 and 0x0600,
# and keeps the names only the second run declares. That is the toolchain
# answering the question rather than anyone's memory of it: a hand written list
# is wrong in both directions, missing what nobody thought of and naming things
# like GetModuleHandleExW that have been there since XP.
#
# CheckXPImports.cmake fails the build when an XP-targeted binary imports one.
'@

if (-not (Get-Command $Compiler -ErrorAction Ignore)) {
    throw "no such compiler: $Compiler -- pass one, or put the 32 bit mingw-w64 gcc on PATH"
}

$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$out  = Join-Path $root 'cmake\xp-forbidden-imports.txt'
$tmp  = Join-Path ([IO.Path]::GetTempPath()) ('xp-imports-' + [guid]::NewGuid())

New-Item -ItemType Directory $tmp | Out-Null

try {
    $all = Join-Path $tmp 'all.h'

    # WriteAllText rather than Set-Content: this file is fed to a C
    # preprocessor, and Windows PowerShell's own redirection writes UTF-16.
    [IO.File]::WriteAllText($all, $headers + "`n")

    # Every identifier followed by "(", which is a superset of the declared
    # functions. Precision is not needed: the two runs differ only where the
    # headers gate on the version, so their difference is the answer whatever
    # else the superset picked up.
    $ident = [regex]'[A-Za-z_][A-Za-z0-9_]*(?=\s*\()'
    $names = @{}

    foreach ($ver in '0x0501', '0x0600') {
        $pp = Join-Path $tmp "pp-$ver.i"

        # -o rather than a redirection, so the preprocessed output goes
        # straight to disk as bytes and PowerShell never re-encodes it.
        #
        # In its own scope for the erroractionpreference: the compiler writes
        # warnings on stderr, Windows PowerShell turns a native command's
        # redirected stderr into an error record, and stop would make a
        # warning fatal. The exit status is what says whether it worked.
        & {
            $ErrorActionPreference = 'Continue'

            & $Compiler -E "-D_WIN32_WINNT=$ver" "-DWINVER=$ver" -D_WIN32_IE=0x0600 `
                        -x c $all -o $pp 2>&1 | Out-Null
        }

        if ($LASTEXITCODE -ne 0) {
            throw "$Compiler failed preprocessing the headers at _WIN32_WINNT=$ver"
        }

        $set = New-Object 'System.Collections.Generic.HashSet[string]' (
            ,[StringComparer]::Ordinal)

        foreach ($m in $ident.Matches([IO.File]::ReadAllText($pp))) {
            [void]$set.Add($m.Value)
        }

        $names[$ver] = $set
    }

    $vista = New-Object 'System.Collections.Generic.HashSet[string]' (
        [string[]]$names['0x0600'], [StringComparer]::Ordinal)

    $vista.ExceptWith($names['0x0501'])

    if ($vista.Count -eq 0) {
        throw 'the two preprocessor runs declared the same names, which cannot be right'
    }

    # Ordinal, to match what the C locale sorted to when this was a shell
    # script, so regenerating does not reshuffle the file.
    [string[]]$sorted = $vista
    [Array]::Sort($sorted, [StringComparer]::Ordinal)

    # LF and no BOM: the file is read by CMake and lives in a repository whose
    # text is LF, and Windows PowerShell would write CRLF and a BOM for both.
    [IO.File]::WriteAllText($out,
        $banner + "`n" + ($sorted -join "`n") + "`n",
        (New-Object System.Text.UTF8Encoding $false))

    "wrote $out ($($sorted.Count) names)"
}
finally {
    Remove-Item -Recurse -Force $tmp -ErrorAction Ignore
}
