services:
  build:
    build: .
    volumes:
      - .:/src
    command:
      - sh
      - -c
      - |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DENABLE_WX=ON -DENABLE_SDL=OFF -DBUILD_TESTING=OFF &&
        cmake --build build --parallel
