# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bbouclet/VBA/vbam/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bbouclet/VBA/vbam/trunk

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake

# Special rule for the target install/local
install/local/fast: install/local

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bbouclet/VBA/vbam/trunk/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bbouclet/VBA/vbam/trunk/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named gvbam

# Build rule for target.
gvbam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gvbam

# fast build rule for target.
gvbam/fast:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/build

#=============================================================================
# Target rules for targets named vbam

# Build rule for target.
vbam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vbam

# fast build rule for target.
vbam/fast:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/build

#=============================================================================
# Target rules for targets named vbamcore

# Build rule for target.
vbamcore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vbamcore

# fast build rule for target.
vbamcore/fast:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/build

# target to build an object file
src/2xSaI.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/2xSaI.o

# target to preprocess a source file
src/2xSaI.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/2xSaI.i

# target to generate assembly for a file
src/2xSaI.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/2xSaI.s

# target to build an object file
src/CheatSearch.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/CheatSearch.o

# target to preprocess a source file
src/CheatSearch.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/CheatSearch.i

# target to generate assembly for a file
src/CheatSearch.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/CheatSearch.s

# target to build an object file
src/Cheats.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Cheats.o

# target to preprocess a source file
src/Cheats.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Cheats.i

# target to generate assembly for a file
src/Cheats.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Cheats.s

# target to build an object file
src/EEprom.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/EEprom.o

# target to preprocess a source file
src/EEprom.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/EEprom.i

# target to generate assembly for a file
src/EEprom.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/EEprom.s

# target to build an object file
src/Flash.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Flash.o

# target to preprocess a source file
src/Flash.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Flash.i

# target to generate assembly for a file
src/Flash.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Flash.s

# target to build an object file
src/Globals.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Globals.o

# target to preprocess a source file
src/Globals.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Globals.i

# target to generate assembly for a file
src/Globals.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Globals.s

# target to build an object file
src/Mode0.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode0.o

# target to preprocess a source file
src/Mode0.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode0.i

# target to generate assembly for a file
src/Mode0.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode0.s

# target to build an object file
src/Mode1.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode1.o

# target to preprocess a source file
src/Mode1.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode1.i

# target to generate assembly for a file
src/Mode1.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode1.s

# target to build an object file
src/Mode2.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode2.o

# target to preprocess a source file
src/Mode2.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode2.i

# target to generate assembly for a file
src/Mode2.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode2.s

# target to build an object file
src/Mode3.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode3.o

# target to preprocess a source file
src/Mode3.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode3.i

# target to generate assembly for a file
src/Mode3.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode3.s

# target to build an object file
src/Mode4.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode4.o

# target to preprocess a source file
src/Mode4.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode4.i

# target to generate assembly for a file
src/Mode4.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode4.s

# target to build an object file
src/Mode5.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode5.o

# target to preprocess a source file
src/Mode5.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode5.i

# target to generate assembly for a file
src/Mode5.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Mode5.s

# target to build an object file
src/RTC.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/RTC.o

# target to preprocess a source file
src/RTC.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/RTC.i

# target to generate assembly for a file
src/RTC.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/RTC.s

# target to build an object file
src/Sound.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Sound.o

# target to preprocess a source file
src/Sound.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Sound.i

# target to generate assembly for a file
src/Sound.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Sound.s

# target to build an object file
src/Sram.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Sram.o

# target to preprocess a source file
src/Sram.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Sram.i

# target to generate assembly for a file
src/Sram.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Sram.s

# target to build an object file
src/Util.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Util.o

# target to preprocess a source file
src/Util.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Util.i

# target to generate assembly for a file
src/Util.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/Util.s

# target to build an object file
src/admame.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/admame.o

# target to preprocess a source file
src/admame.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/admame.i

# target to generate assembly for a file
src/admame.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/admame.s

# target to build an object file
src/agb/GBA-arm.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBA-arm.o

# target to preprocess a source file
src/agb/GBA-arm.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBA-arm.i

# target to generate assembly for a file
src/agb/GBA-arm.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBA-arm.s

# target to build an object file
src/agb/GBA-thumb.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBA-thumb.o

# target to preprocess a source file
src/agb/GBA-thumb.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBA-thumb.i

# target to generate assembly for a file
src/agb/GBA-thumb.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBA-thumb.s

# target to build an object file
src/agb/GBA.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBA.o

# target to preprocess a source file
src/agb/GBA.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBA.i

# target to generate assembly for a file
src/agb/GBA.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBA.s

# target to build an object file
src/agb/GBAGfx.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBAGfx.o

# target to preprocess a source file
src/agb/GBAGfx.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBAGfx.i

# target to generate assembly for a file
src/agb/GBAGfx.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/GBAGfx.s

# target to build an object file
src/agb/agbprint.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/agbprint.o

# target to preprocess a source file
src/agb/agbprint.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/agbprint.i

# target to generate assembly for a file
src/agb/agbprint.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/agbprint.s

# target to build an object file
src/agb/gbafilter.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/gbafilter.o

# target to preprocess a source file
src/agb/gbafilter.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/gbafilter.i

# target to generate assembly for a file
src/agb/gbafilter.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/agb/gbafilter.s

# target to build an object file
src/armdis.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/armdis.o

# target to preprocess a source file
src/armdis.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/armdis.i

# target to generate assembly for a file
src/armdis.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/armdis.s

# target to build an object file
src/bilinear.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/bilinear.o

# target to preprocess a source file
src/bilinear.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/bilinear.i

# target to generate assembly for a file
src/bilinear.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/bilinear.s

# target to build an object file
src/bios.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/bios.o

# target to preprocess a source file
src/bios.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/bios.i

# target to generate assembly for a file
src/bios.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/bios.s

# target to build an object file
src/dmg/GB.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/GB.o

# target to preprocess a source file
src/dmg/GB.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/GB.i

# target to generate assembly for a file
src/dmg/GB.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/GB.s

# target to build an object file
src/dmg/gbCheats.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbCheats.o

# target to preprocess a source file
src/dmg/gbCheats.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbCheats.i

# target to generate assembly for a file
src/dmg/gbCheats.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbCheats.s

# target to build an object file
src/dmg/gbDis.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbDis.o

# target to preprocess a source file
src/dmg/gbDis.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbDis.i

# target to generate assembly for a file
src/dmg/gbDis.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbDis.s

# target to build an object file
src/dmg/gbGfx.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbGfx.o

# target to preprocess a source file
src/dmg/gbGfx.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbGfx.i

# target to generate assembly for a file
src/dmg/gbGfx.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbGfx.s

# target to build an object file
src/dmg/gbGlobals.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbGlobals.o

# target to preprocess a source file
src/dmg/gbGlobals.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbGlobals.i

# target to generate assembly for a file
src/dmg/gbGlobals.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbGlobals.s

# target to build an object file
src/dmg/gbMemory.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbMemory.o

# target to preprocess a source file
src/dmg/gbMemory.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbMemory.i

# target to generate assembly for a file
src/dmg/gbMemory.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbMemory.s

# target to build an object file
src/dmg/gbPrinter.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbPrinter.o

# target to preprocess a source file
src/dmg/gbPrinter.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbPrinter.i

# target to generate assembly for a file
src/dmg/gbPrinter.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbPrinter.s

# target to build an object file
src/dmg/gbSGB.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbSGB.o

# target to preprocess a source file
src/dmg/gbSGB.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbSGB.i

# target to generate assembly for a file
src/dmg/gbSGB.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbSGB.s

# target to build an object file
src/dmg/gbSound.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbSound.o

# target to preprocess a source file
src/dmg/gbSound.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbSound.i

# target to generate assembly for a file
src/dmg/gbSound.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gbSound.s

# target to build an object file
src/dmg/gb_apu/Blip_Buffer.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Blip_Buffer.o

# target to preprocess a source file
src/dmg/gb_apu/Blip_Buffer.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Blip_Buffer.i

# target to generate assembly for a file
src/dmg/gb_apu/Blip_Buffer.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Blip_Buffer.s

# target to build an object file
src/dmg/gb_apu/Effects_Buffer.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Effects_Buffer.o

# target to preprocess a source file
src/dmg/gb_apu/Effects_Buffer.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Effects_Buffer.i

# target to generate assembly for a file
src/dmg/gb_apu/Effects_Buffer.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Effects_Buffer.s

# target to build an object file
src/dmg/gb_apu/Gb_Apu.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Gb_Apu.o

# target to preprocess a source file
src/dmg/gb_apu/Gb_Apu.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Gb_Apu.i

# target to generate assembly for a file
src/dmg/gb_apu/Gb_Apu.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Gb_Apu.s

# target to build an object file
src/dmg/gb_apu/Gb_Apu_State.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Gb_Apu_State.o

# target to preprocess a source file
src/dmg/gb_apu/Gb_Apu_State.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Gb_Apu_State.i

# target to generate assembly for a file
src/dmg/gb_apu/Gb_Apu_State.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Gb_Apu_State.s

# target to build an object file
src/dmg/gb_apu/Gb_Oscs.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Gb_Oscs.o

# target to preprocess a source file
src/dmg/gb_apu/Gb_Oscs.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Gb_Oscs.i

# target to generate assembly for a file
src/dmg/gb_apu/Gb_Oscs.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Gb_Oscs.s

# target to build an object file
src/dmg/gb_apu/Multi_Buffer.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Multi_Buffer.o

# target to preprocess a source file
src/dmg/gb_apu/Multi_Buffer.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Multi_Buffer.i

# target to generate assembly for a file
src/dmg/gb_apu/Multi_Buffer.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/dmg/gb_apu/Multi_Buffer.s

# target to build an object file
src/elf.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/elf.o

# target to preprocess a source file
src/elf.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/elf.i

# target to generate assembly for a file
src/elf.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/elf.s

# target to build an object file
src/expr-lex.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/expr-lex.o

# target to preprocess a source file
src/expr-lex.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/expr-lex.i

# target to generate assembly for a file
src/expr-lex.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/expr-lex.s

# target to build an object file
src/expr.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/expr.o

# target to preprocess a source file
src/expr.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/expr.i

# target to generate assembly for a file
src/expr.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/expr.s

# target to build an object file
src/exprNode.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/exprNode.o

# target to preprocess a source file
src/exprNode.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/exprNode.i

# target to generate assembly for a file
src/exprNode.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/exprNode.s

# target to build an object file
src/fex_mini.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/fex_mini.o

# target to preprocess a source file
src/fex_mini.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/fex_mini.i

# target to generate assembly for a file
src/fex_mini.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/fex_mini.s

# target to build an object file
src/gtk/configfile.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/configfile.o

# target to preprocess a source file
src/gtk/configfile.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/configfile.i

# target to generate assembly for a file
src/gtk/configfile.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/configfile.s

# target to build an object file
src/gtk/filters.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/filters.o

# target to preprocess a source file
src/gtk/filters.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/filters.i

# target to generate assembly for a file
src/gtk/filters.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/filters.s

# target to build an object file
src/gtk/input.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/input.o

# target to preprocess a source file
src/gtk/input.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/input.i

# target to generate assembly for a file
src/gtk/input.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/input.s

# target to build an object file
src/gtk/joypadconfig.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/joypadconfig.o

# target to preprocess a source file
src/gtk/joypadconfig.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/joypadconfig.i

# target to generate assembly for a file
src/gtk/joypadconfig.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/joypadconfig.s

# target to build an object file
src/gtk/main.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/main.o

# target to preprocess a source file
src/gtk/main.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/main.i

# target to generate assembly for a file
src/gtk/main.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/main.s

# target to build an object file
src/gtk/screenarea.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/screenarea.o

# target to preprocess a source file
src/gtk/screenarea.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/screenarea.i

# target to generate assembly for a file
src/gtk/screenarea.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/screenarea.s

# target to build an object file
src/gtk/sndPortAudio.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/sndPortAudio.o

# target to preprocess a source file
src/gtk/sndPortAudio.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/sndPortAudio.i

# target to generate assembly for a file
src/gtk/sndPortAudio.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/sndPortAudio.s

# target to build an object file
src/gtk/system.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/system.o

# target to preprocess a source file
src/gtk/system.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/system.i

# target to generate assembly for a file
src/gtk/system.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/system.s

# target to build an object file
src/gtk/tools.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/tools.o

# target to preprocess a source file
src/gtk/tools.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/tools.i

# target to generate assembly for a file
src/gtk/tools.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/tools.s

# target to build an object file
src/gtk/window.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/window.o

# target to preprocess a source file
src/gtk/window.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/window.i

# target to generate assembly for a file
src/gtk/window.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/window.s

# target to build an object file
src/gtk/windowcallbacks.o:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/windowcallbacks.o

# target to preprocess a source file
src/gtk/windowcallbacks.i:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/windowcallbacks.i

# target to generate assembly for a file
src/gtk/windowcallbacks.s:
	$(MAKE) -f CMakeFiles/gvbam.dir/build.make CMakeFiles/gvbam.dir/src/gtk/windowcallbacks.s

# target to build an object file
src/hq/c/hq_implementation.o:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/hq/c/hq_implementation.o

# target to preprocess a source file
src/hq/c/hq_implementation.i:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/hq/c/hq_implementation.i

# target to generate assembly for a file
src/hq/c/hq_implementation.s:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/hq/c/hq_implementation.s

# target to build an object file
src/hq2x.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/hq2x.o

# target to preprocess a source file
src/hq2x.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/hq2x.i

# target to generate assembly for a file
src/hq2x.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/hq2x.s

# target to build an object file
src/interframe.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/interframe.o

# target to preprocess a source file
src/interframe.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/interframe.i

# target to generate assembly for a file
src/interframe.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/interframe.s

# target to build an object file
src/memgzio.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/memgzio.o

# target to preprocess a source file
src/memgzio.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/memgzio.i

# target to generate assembly for a file
src/memgzio.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/memgzio.s

# target to build an object file
src/pixel.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/pixel.o

# target to preprocess a source file
src/pixel.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/pixel.i

# target to generate assembly for a file
src/pixel.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/pixel.s

# target to build an object file
src/remote.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/remote.o

# target to preprocess a source file
src/remote.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/remote.i

# target to generate assembly for a file
src/remote.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/remote.s

# target to build an object file
src/scanline.o:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/scanline.o

# target to preprocess a source file
src/scanline.i:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/scanline.i

# target to generate assembly for a file
src/scanline.s:
	$(MAKE) -f CMakeFiles/vbamcore.dir/build.make CMakeFiles/vbamcore.dir/src/scanline.s

# target to build an object file
src/sdl/SDL.o:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/SDL.o

# target to preprocess a source file
src/sdl/SDL.i:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/SDL.i

# target to generate assembly for a file
src/sdl/SDL.s:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/SDL.s

# target to build an object file
src/sdl/debugger.o:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/debugger.o

# target to preprocess a source file
src/sdl/debugger.i:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/debugger.i

# target to generate assembly for a file
src/sdl/debugger.s:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/debugger.s

# target to build an object file
src/sdl/dummy.o:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/dummy.o

# target to preprocess a source file
src/sdl/dummy.i:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/dummy.i

# target to generate assembly for a file
src/sdl/dummy.s:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/dummy.s

# target to build an object file
src/sdl/filters.o:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/filters.o

# target to preprocess a source file
src/sdl/filters.i:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/filters.i

# target to generate assembly for a file
src/sdl/filters.s:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/filters.s

# target to build an object file
src/sdl/sndSDL.o:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/sndSDL.o

# target to preprocess a source file
src/sdl/sndSDL.i:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/sndSDL.i

# target to generate assembly for a file
src/sdl/sndSDL.s:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/sndSDL.s

# target to build an object file
src/sdl/text.o:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/text.o

# target to preprocess a source file
src/sdl/text.i:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/text.i

# target to generate assembly for a file
src/sdl/text.s:
	$(MAKE) -f CMakeFiles/vbam.dir/build.make CMakeFiles/vbam.dir/src/sdl/text.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gvbam"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vbam"
	@echo "... vbamcore"
	@echo "... src/2xSaI.o"
	@echo "... src/2xSaI.i"
	@echo "... src/2xSaI.s"
	@echo "... src/CheatSearch.o"
	@echo "... src/CheatSearch.i"
	@echo "... src/CheatSearch.s"
	@echo "... src/Cheats.o"
	@echo "... src/Cheats.i"
	@echo "... src/Cheats.s"
	@echo "... src/EEprom.o"
	@echo "... src/EEprom.i"
	@echo "... src/EEprom.s"
	@echo "... src/Flash.o"
	@echo "... src/Flash.i"
	@echo "... src/Flash.s"
	@echo "... src/Globals.o"
	@echo "... src/Globals.i"
	@echo "... src/Globals.s"
	@echo "... src/Mode0.o"
	@echo "... src/Mode0.i"
	@echo "... src/Mode0.s"
	@echo "... src/Mode1.o"
	@echo "... src/Mode1.i"
	@echo "... src/Mode1.s"
	@echo "... src/Mode2.o"
	@echo "... src/Mode2.i"
	@echo "... src/Mode2.s"
	@echo "... src/Mode3.o"
	@echo "... src/Mode3.i"
	@echo "... src/Mode3.s"
	@echo "... src/Mode4.o"
	@echo "... src/Mode4.i"
	@echo "... src/Mode4.s"
	@echo "... src/Mode5.o"
	@echo "... src/Mode5.i"
	@echo "... src/Mode5.s"
	@echo "... src/RTC.o"
	@echo "... src/RTC.i"
	@echo "... src/RTC.s"
	@echo "... src/Sound.o"
	@echo "... src/Sound.i"
	@echo "... src/Sound.s"
	@echo "... src/Sram.o"
	@echo "... src/Sram.i"
	@echo "... src/Sram.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/admame.o"
	@echo "... src/admame.i"
	@echo "... src/admame.s"
	@echo "... src/agb/GBA-arm.o"
	@echo "... src/agb/GBA-arm.i"
	@echo "... src/agb/GBA-arm.s"
	@echo "... src/agb/GBA-thumb.o"
	@echo "... src/agb/GBA-thumb.i"
	@echo "... src/agb/GBA-thumb.s"
	@echo "... src/agb/GBA.o"
	@echo "... src/agb/GBA.i"
	@echo "... src/agb/GBA.s"
	@echo "... src/agb/GBAGfx.o"
	@echo "... src/agb/GBAGfx.i"
	@echo "... src/agb/GBAGfx.s"
	@echo "... src/agb/agbprint.o"
	@echo "... src/agb/agbprint.i"
	@echo "... src/agb/agbprint.s"
	@echo "... src/agb/gbafilter.o"
	@echo "... src/agb/gbafilter.i"
	@echo "... src/agb/gbafilter.s"
	@echo "... src/armdis.o"
	@echo "... src/armdis.i"
	@echo "... src/armdis.s"
	@echo "... src/bilinear.o"
	@echo "... src/bilinear.i"
	@echo "... src/bilinear.s"
	@echo "... src/bios.o"
	@echo "... src/bios.i"
	@echo "... src/bios.s"
	@echo "... src/dmg/GB.o"
	@echo "... src/dmg/GB.i"
	@echo "... src/dmg/GB.s"
	@echo "... src/dmg/gbCheats.o"
	@echo "... src/dmg/gbCheats.i"
	@echo "... src/dmg/gbCheats.s"
	@echo "... src/dmg/gbDis.o"
	@echo "... src/dmg/gbDis.i"
	@echo "... src/dmg/gbDis.s"
	@echo "... src/dmg/gbGfx.o"
	@echo "... src/dmg/gbGfx.i"
	@echo "... src/dmg/gbGfx.s"
	@echo "... src/dmg/gbGlobals.o"
	@echo "... src/dmg/gbGlobals.i"
	@echo "... src/dmg/gbGlobals.s"
	@echo "... src/dmg/gbMemory.o"
	@echo "... src/dmg/gbMemory.i"
	@echo "... src/dmg/gbMemory.s"
	@echo "... src/dmg/gbPrinter.o"
	@echo "... src/dmg/gbPrinter.i"
	@echo "... src/dmg/gbPrinter.s"
	@echo "... src/dmg/gbSGB.o"
	@echo "... src/dmg/gbSGB.i"
	@echo "... src/dmg/gbSGB.s"
	@echo "... src/dmg/gbSound.o"
	@echo "... src/dmg/gbSound.i"
	@echo "... src/dmg/gbSound.s"
	@echo "... src/dmg/gb_apu/Blip_Buffer.o"
	@echo "... src/dmg/gb_apu/Blip_Buffer.i"
	@echo "... src/dmg/gb_apu/Blip_Buffer.s"
	@echo "... src/dmg/gb_apu/Effects_Buffer.o"
	@echo "... src/dmg/gb_apu/Effects_Buffer.i"
	@echo "... src/dmg/gb_apu/Effects_Buffer.s"
	@echo "... src/dmg/gb_apu/Gb_Apu.o"
	@echo "... src/dmg/gb_apu/Gb_Apu.i"
	@echo "... src/dmg/gb_apu/Gb_Apu.s"
	@echo "... src/dmg/gb_apu/Gb_Apu_State.o"
	@echo "... src/dmg/gb_apu/Gb_Apu_State.i"
	@echo "... src/dmg/gb_apu/Gb_Apu_State.s"
	@echo "... src/dmg/gb_apu/Gb_Oscs.o"
	@echo "... src/dmg/gb_apu/Gb_Oscs.i"
	@echo "... src/dmg/gb_apu/Gb_Oscs.s"
	@echo "... src/dmg/gb_apu/Multi_Buffer.o"
	@echo "... src/dmg/gb_apu/Multi_Buffer.i"
	@echo "... src/dmg/gb_apu/Multi_Buffer.s"
	@echo "... src/elf.o"
	@echo "... src/elf.i"
	@echo "... src/elf.s"
	@echo "... src/expr-lex.o"
	@echo "... src/expr-lex.i"
	@echo "... src/expr-lex.s"
	@echo "... src/expr.o"
	@echo "... src/expr.i"
	@echo "... src/expr.s"
	@echo "... src/exprNode.o"
	@echo "... src/exprNode.i"
	@echo "... src/exprNode.s"
	@echo "... src/fex_mini.o"
	@echo "... src/fex_mini.i"
	@echo "... src/fex_mini.s"
	@echo "... src/gtk/configfile.o"
	@echo "... src/gtk/configfile.i"
	@echo "... src/gtk/configfile.s"
	@echo "... src/gtk/filters.o"
	@echo "... src/gtk/filters.i"
	@echo "... src/gtk/filters.s"
	@echo "... src/gtk/input.o"
	@echo "... src/gtk/input.i"
	@echo "... src/gtk/input.s"
	@echo "... src/gtk/joypadconfig.o"
	@echo "... src/gtk/joypadconfig.i"
	@echo "... src/gtk/joypadconfig.s"
	@echo "... src/gtk/main.o"
	@echo "... src/gtk/main.i"
	@echo "... src/gtk/main.s"
	@echo "... src/gtk/screenarea.o"
	@echo "... src/gtk/screenarea.i"
	@echo "... src/gtk/screenarea.s"
	@echo "... src/gtk/sndPortAudio.o"
	@echo "... src/gtk/sndPortAudio.i"
	@echo "... src/gtk/sndPortAudio.s"
	@echo "... src/gtk/system.o"
	@echo "... src/gtk/system.i"
	@echo "... src/gtk/system.s"
	@echo "... src/gtk/tools.o"
	@echo "... src/gtk/tools.i"
	@echo "... src/gtk/tools.s"
	@echo "... src/gtk/window.o"
	@echo "... src/gtk/window.i"
	@echo "... src/gtk/window.s"
	@echo "... src/gtk/windowcallbacks.o"
	@echo "... src/gtk/windowcallbacks.i"
	@echo "... src/gtk/windowcallbacks.s"
	@echo "... src/hq/c/hq_implementation.o"
	@echo "... src/hq/c/hq_implementation.i"
	@echo "... src/hq/c/hq_implementation.s"
	@echo "... src/hq2x.o"
	@echo "... src/hq2x.i"
	@echo "... src/hq2x.s"
	@echo "... src/interframe.o"
	@echo "... src/interframe.i"
	@echo "... src/interframe.s"
	@echo "... src/memgzio.o"
	@echo "... src/memgzio.i"
	@echo "... src/memgzio.s"
	@echo "... src/pixel.o"
	@echo "... src/pixel.i"
	@echo "... src/pixel.s"
	@echo "... src/remote.o"
	@echo "... src/remote.i"
	@echo "... src/remote.s"
	@echo "... src/scanline.o"
	@echo "... src/scanline.i"
	@echo "... src/scanline.s"
	@echo "... src/sdl/SDL.o"
	@echo "... src/sdl/SDL.i"
	@echo "... src/sdl/SDL.s"
	@echo "... src/sdl/debugger.o"
	@echo "... src/sdl/debugger.i"
	@echo "... src/sdl/debugger.s"
	@echo "... src/sdl/dummy.o"
	@echo "... src/sdl/dummy.i"
	@echo "... src/sdl/dummy.s"
	@echo "... src/sdl/filters.o"
	@echo "... src/sdl/filters.i"
	@echo "... src/sdl/filters.s"
	@echo "... src/sdl/sndSDL.o"
	@echo "... src/sdl/sndSDL.i"
	@echo "... src/sdl/sndSDL.s"
	@echo "... src/sdl/text.o"
	@echo "... src/sdl/text.i"
	@echo "... src/sdl/text.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

