.TH gvbam 1 "March 28, 2012"
.SH NAME
VBAM-GTK \- (aka
.B gvbam
) A gtk GUI for a high compatibility Gameboy Advance
Emulator combining Visual Boy Advance developments.
.SH SYNOPSIS
.B GVBAM
.RI [ options ]
.SH DESCRIPTION
.B VisualBoyAdvance-M
is a Nintendo Game Boy Emulator with high compatibility with
commercial games.
.P
It emulates the Nintendo Game Boy Advance hand held console, in
addition to the original Game Boy hand held systems and its Super and Color
variants.
.P
VBA-M is a continued development of the now inactive VisualBoy
Advance project, with many improvements from various developments of VBA.
.P
This application is the GTK GUI version of VisualBoyAdvance-M.
.SH OPTIONS
.TP
.BI "\-h, \-\-help
Output version information
.TP
.B \-v, \-\-version
Output version information
.SH AUTHOR
This manual page was written by Jeremy Newton <alexjnewt@hotmail.com>,
for the RPMFusion and VBAM. This man page can be free used by anyone.
