.TH visualboyadvance-m 6 "December 10, 2016"
.SH NAME
VisualBoyAdvance-M - A wxWidgets GUI for a high compatibility Gameboy Advance
Emulator integrating the best features from various Visual Boy Advance builds.
.SH SYNOPSIS
.B visualboyadvance-m
.RI [ options ]
.SH DESCRIPTION
.B VisualBoyAdvance-M
is a Nintendo Game Boy Emulator with high compatibility with
commercial games.
.P
It emulates the Nintendo Game Boy Advance hand held console, in
addition to the original Game Boy hand held systems and its Super and Color
variants.
.P
VBA-M is a continued development of the now inactive VisualBoy
Advance project, with many improvements from various builds of VBA.
.P
This application is the wxWidgets GUI version of VisualBoyAdvance-M.
.SH OPTIONS
.TP
.BI "\-h, \-\-help
Show help message
.TP
.B \-\-verbose
Generate verbose log messages
.TP
.B \-\-save-xrc=<str>
Save built-in XRC file and exit
.TP
.B \-\-save-over=<str>
Save built-in vba-over.ini and exit
.TP
.B \-\-print-cfg-path
Print configuration path and exit
.TP
.B \-f, \-\-fullscreen
Start in full-screen mode
.TP
.B \-s, \-\-delete-shared-state
Delete shared link state first, if it exists
.TP
.B \-o, \-\-list-options
List all settable options and exit
.SH AUTHOR
This manual page was written by Jeremy Newton (Mystro256).
This man page is licensed as GPLv2 or later.
