#ifndef VBAM_WX_RPI_PROXY_RPI_HOST_PATH_H_
#define VBAM_WX_RPI_PROXY_RPI_HOST_PATH_H_

// Path to the 32-bit RPI host executable for resource embedding
// This file is auto-generated by CMake
#define RPI_HOST_EXE_PATH "C:/Users/rkito/source/repos/visualboyadvance-m/build-x64-rel/rpi-host-x86/install/vbam-rpi-host.exe"

#endif  // VBAM_WX_RPI_PROXY_RPI_HOST_PATH_H_
