// GBA I/O register table for the IO Viewer. Copied from the wx port's
// ioregs.h (itself a copy of ../win32/IOViewRegisters.h). The strings are
// translated at use with QCoreApplication::translate("IOViewer", ...);
// QT_TRANSLATE_NOOP keeps them visible to lupdate.
//
// Include only from viewers.cpp, after core/gba/gbaGlobals.h.
struct IOData {
    uint16_t* address;
    uint16_t offset;
    const char* name;
    uint16_t write;
    const char* bits[16];
};

static const IOData ioregs[] =
    {
      { &DISPCNT,
          0,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000000-DISPCNT"),
          0xFFF7,
          { "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "BG Mode (3 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "CGB Mode"),
              QT_TRANSLATE_NOOP("IOViewer", "Display Frame"),
              QT_TRANSLATE_NOOP("IOViewer", "H-Blank Interval OBJ processing"),
              QT_TRANSLATE_NOOP("IOViewer", "OBJ Character mapping"),
              QT_TRANSLATE_NOOP("IOViewer", "Forced blank"),
              QT_TRANSLATE_NOOP("IOViewer", "BG0"),
              QT_TRANSLATE_NOOP("IOViewer", "BG1"),
              QT_TRANSLATE_NOOP("IOViewer", "BG2"),
              QT_TRANSLATE_NOOP("IOViewer", "BG3"),
              QT_TRANSLATE_NOOP("IOViewer", "OBJ"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN1"),
              QT_TRANSLATE_NOOP("IOViewer", "OBJWIN") } },
      { &DISPSTAT,
          4,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000004-DISPSTAT"),
          0xFF38,
          { QT_TRANSLATE_NOOP("IOViewer", "V-Blank Status"),
              QT_TRANSLATE_NOOP("IOViewer", "H-Blank Status"),
              QT_TRANSLATE_NOOP("IOViewer", "VCOUNT Evaluation"),
              QT_TRANSLATE_NOOP("IOViewer", "V-Blank Interrupt Enable"),
              QT_TRANSLATE_NOOP("IOViewer", "H-Blank Interrupt Enable"),
              QT_TRANSLATE_NOOP("IOViewer", "VCOUNT Match Interrupt Enable"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "VCOUNT setting (8 bits)") } },
      { &VCOUNT,
          6,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000006-VCOUNT"),
          0x0000,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "VCOUNT (8 bits)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "" } },
      { &BG0CNT,
          8,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000008-BG0CNT"),
          0xDFCF,
          { "",
              QT_TRANSLATE_NOOP("IOViewer", "Priority (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Char base (2 bits)"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Mosaic"),
              QT_TRANSLATE_NOOP("IOViewer", "16/256 colors"),
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Screen Base Block (5 bits)"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Size (2 bits)") } },
      { &BG1CNT,
          0xA,
          QT_TRANSLATE_NOOP("IOViewer", "0x400000A-BG1CNT"),
          0xDFCF,
          { "",
              QT_TRANSLATE_NOOP("IOViewer", "Priority (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Char base (2 bits)"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Mosaic"),
              QT_TRANSLATE_NOOP("IOViewer", "16/256 colors"),
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Screen Base Block (5 bits)"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Size (2 bits)") } },
      { &BG2CNT,
          0xC,
          QT_TRANSLATE_NOOP("IOViewer", "0x400000C-BG2CNT"),
          0xFFCF,
          { "",
              QT_TRANSLATE_NOOP("IOViewer", "Priority (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Char base (2 bits)"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Mosaic"),
              QT_TRANSLATE_NOOP("IOViewer", "16/256 colors"),
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Screen Base Block (5 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Area Overflow"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Size (2 bits)") } },
      { &BG3CNT,
          0xE,
          QT_TRANSLATE_NOOP("IOViewer", "0x400000E-BG3CNT"),
          0xFFCF,
          { "",
              QT_TRANSLATE_NOOP("IOViewer", "Priority (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Char base (2 bits)"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Mosaic"),
              QT_TRANSLATE_NOOP("IOViewer", "16/256 colors"),
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Screen Base Block (5 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Area Overflow"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Size (2 bits)") } },
      { &BG0HOFS,
          0x10,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000010-BG0HOFS"),
          0x01FF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Horizontal Offset (9 bits, W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "" } },
      { &BG0VOFS,
          0x12,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000012-BG0VOFS"),
          0x01FF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Vertical Offset (9 bits, W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "" } },
      { &BG1HOFS,
          0x14,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000014-BG1HOFS"),
          0x01FF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Horizontal Offset (9 bits, W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "" } },
      { &BG1VOFS,
          0x16,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000016-BG1VOFS"),
          0x01FF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Vertical Offset (9 bits, W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "" } },
      { &BG2HOFS,
          0x18,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000018-BG2HOFS"),
          0x01FF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Horizontal Offset (9 bits, W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "" } },
      { &BG2VOFS,
          0x1A,
          QT_TRANSLATE_NOOP("IOViewer", "0x400001A-BG2VOFS"),
          0x01FF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Vertical Offset (9 bits, W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "" } },
      { &BG3HOFS,
          0x1C,
          QT_TRANSLATE_NOOP("IOViewer", "0x400001C-BG3HOFS"),
          0x01FF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Horizontal Offset (9 bits,W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "" } },
      { &BG3VOFS,
          0x1E,
          QT_TRANSLATE_NOOP("IOViewer", "0x400001E-BG3VOFS"),
          0x01FF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Vertical Offset (9 bits,W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "" } },
      { &BG2PA,
          0x20,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000020-BG2PA"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "dx (16 bits,W)") } },
      { &BG2PB,
          0x22,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000022-BG2PB"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "dmx (16 bits,W)") } },
      { &BG2PC,
          0x24,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000024-BG2PC"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "dy (16 bits,W)") } },
      { &BG2PD,
          0x26,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000026-BG2PD"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "dmy (16 bits,W)") } },
      { &BG2X_L,
          0x28,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000028-BG2X_L"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "X low bits (16 bits,W)") } },
      { &BG2X_H,
          0x2A,
          QT_TRANSLATE_NOOP("IOViewer", "0x400002A-BG2X_H"),
          0x0FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "X high bits (12 bits,W)"),
              "",
              "",
              "",
              "",
          } },
      { &BG2Y_L,
          0x2C,
          QT_TRANSLATE_NOOP("IOViewer", "0x400002C-BG2Y_L"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Y low bits (16 bits,W)") } },
      { &BG2Y_H,
          0x2E,
          QT_TRANSLATE_NOOP("IOViewer", "0x400002E-BG2Y_H"),
          0x0FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Y hight bits (12 bits,W)"),
              "",
              "",
              "",
              "",
          } },
      { &BG3PA,
          0x30,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000030-BG3PA"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "dx (16 bits,W)") } },
      { &BG3PB,
          0x32,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000032-BG3PB"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "dmx (16 bits,W)") } },
      { &BG3PC,
          0x34,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000034-BG3PC"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "dy (16 bits,W)") } },
      { &BG3PD,
          0x36,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000036-BG3PD"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "dmy (16 bits,W)") } },
      { &BG3X_L,
          0x38,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000038-BG3X_L"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "X low bits (16 bits,W)") } },
      { &BG3X_H,
          0x3A,
          QT_TRANSLATE_NOOP("IOViewer", "0x400003A-BG3X_H"),
          0x0FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "X hight bits (12 bits,W)"),
              "",
              "",
              "",
              "",
          } },
      { &BG3Y_L,
          0x3C,
          QT_TRANSLATE_NOOP("IOViewer", "0x400003C-BG3Y_L"),
          0xFFFF,
          { "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Y low bits (16 bits,W)") } },
      { &BG3Y_H,
          0x3E,
          QT_TRANSLATE_NOOP("IOViewer", "0x400003E-BG3Y_H"),
          0x0FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Y hight bits (12 bits,W)"),
              "",
              "",
              "",
              "",
          } },
      { &WIN0H,
          0x40,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000040-WIN0H"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Win 0 lower-right X (8 bits,W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Win 0 upper-left X (8 bits,W)"),
          } },
      { &WIN1H,
          0x42,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000042-WIN1H"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Win 1 lower-right X (8 bits,W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Win 1 upper-left (8 bits,W)"),
          } },
      { &WIN0V,
          0x44,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000044-WIN0V"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Win 0 lower-right Y (8 bits,W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Win 0 upper-left Y (8 bits,W)"),
          } },
      { &WIN1V,
          0x46,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000046-WIN1V"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Win 1 lower-right Y (8 bits,W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Win 1 upper-left Y (8 bits,W)"),
          } },
      { &WININ,
          0x48,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000048-WININ"),
          0x3F3F,
          {
              QT_TRANSLATE_NOOP("IOViewer", "WIN0 BG0"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0 BG1"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0 BG2"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0 BG3"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0 OBJ"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0 Special FX"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "WIN1 BG0"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN1 BG1"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN1 BG2"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN1 BG3"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN1 OBJ"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN1 Special FX"),
              "",
              "",
          } },
      { &WINOUT,
          0x4A,
          QT_TRANSLATE_NOOP("IOViewer", "0x400004A-WINOUT"),
          0x3F3F,
          {
              QT_TRANSLATE_NOOP("IOViewer", "WIN0/1 BG0"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0/1 BG1"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0/1 BG2"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0/1 BG3"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0/1 OBJ"),
              QT_TRANSLATE_NOOP("IOViewer", "WIN0/1 Special FX"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "OBJWIN BG0"),
              QT_TRANSLATE_NOOP("IOViewer", "OBJWIN BG1"),
              QT_TRANSLATE_NOOP("IOViewer", "OBJWIN BG2"),
              QT_TRANSLATE_NOOP("IOViewer", "OBJWIN BG3"),
              QT_TRANSLATE_NOOP("IOViewer", "OBJWIN OBJ"),
              QT_TRANSLATE_NOOP("IOViewer", "OBJWIN Special FX"),
              "",
              "",
          } },
      { &MOSAIC,
          0x4C,
          QT_TRANSLATE_NOOP("IOViewer", "0x400004C-MOSAIC"),
          0xFFFF,
          {
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "BG H Size (4 bits,W)"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "BG V Size (4 bits,W)"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "OBJ H Size (4 bits,W)"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "OBJ V Size (4 bits,W)"),
          } },
      { &BLDMOD,
          0x50,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000050-BLDMOD"),
          0x3FFF,
          {
              QT_TRANSLATE_NOOP("IOViewer", "1st BG0"),
              QT_TRANSLATE_NOOP("IOViewer", "1st BG1"),
              QT_TRANSLATE_NOOP("IOViewer", "1st BG2"),
              QT_TRANSLATE_NOOP("IOViewer", "1st BG3"),
              QT_TRANSLATE_NOOP("IOViewer", "1st OBJ"),
              QT_TRANSLATE_NOOP("IOViewer", "1st BD"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "FX Type (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "2nd BG0"),
              QT_TRANSLATE_NOOP("IOViewer", "2nd BG1"),
              QT_TRANSLATE_NOOP("IOViewer", "2nd BG2"),
              QT_TRANSLATE_NOOP("IOViewer", "2nd BG3"),
              QT_TRANSLATE_NOOP("IOViewer", "2nd OBJ"),
              QT_TRANSLATE_NOOP("IOViewer", "2nd BD"),
              "",
              "",
          } },
      { &COLEV,
          0x52,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000052-COLEV"),
          0x1F1F,
          {
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Coefficient EVA (5 bits,W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Coefficient EVB (5 bits,W)"),
              "",
              "",
              "",
          } },
      { &COLY,
          0x54,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000054-COLEY"),
          0x001F,
          {
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Coefficient EVY (5 bits,W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { nullptr,
          0x60,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000060-SG10_L"),
          0x007F,
          {
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sweep Shifts (3 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Sweep addition/decrease"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sweep Time (3 bits)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { nullptr,
          0x62,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000062-SG10_H"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sound Length (6 bits,W)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Waveform Type (2 bits)"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Envelope Steps (3 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Envelope Attenuate/Amplify"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Envelope Initial Value"),
          } },
      { nullptr,
          0x64,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000064-SG11"),
          0xC7FF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Frequency (11 bits,W)"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sound Continuous/Counter"),
              QT_TRANSLATE_NOOP("IOViewer", "Initialization (W)"),
          } },
      { nullptr,
          0x68,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000068-SG20"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sound Length (6 bits,W)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Waveform Type (2 bits)"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Envelope Steps (3 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Envelope Attenuate/Amplify"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Envelope Initial Value"),
          } },
      { nullptr,
          0x6C,
          QT_TRANSLATE_NOOP("IOViewer", "0x400006C-SG21"),
          0xC7FF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Frequency (11 bits,W)"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sound Continuous/Counter"),
              QT_TRANSLATE_NOOP("IOViewer", "Initialization (W)"),
          } },
      { nullptr,
          0x70,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000070-SG30_L"),
          0x00E0,
          {
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Waveform 32/64 Steps"),
              QT_TRANSLATE_NOOP("IOViewer", "Waveform Bank 0/1"),
              QT_TRANSLATE_NOOP("IOViewer", "Sound Output"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { nullptr,
          0x72,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000072-SG30_H"),
          0xE0FF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sound Length (8 bits,W)"),
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Output Level (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Forced 3/4 Output Level"),
          } },
      { nullptr,
          0x74,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000074-SG31"),
          0xC7FF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Frequency (11 bits,W)"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sound Continuous/Counter"),
              QT_TRANSLATE_NOOP("IOViewer", "Initialization (W)"),
          } },
      { nullptr,
          0x78,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000078-SG40"),
          0xFF3F,
          {
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sound Length (6 bits,W)"),
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Envelope Steps (3 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Envelope Attenuate/Amplify"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Envelope Initial Value"),
          } },
      { nullptr,
          0x7C,
          QT_TRANSLATE_NOOP("IOViewer", "0x400007C-SG41"),
          0xC0FF,
          {
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Dividing Ratio Freq. (3 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Counter 15/7 Steps"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Counter Shift Clock (4 bits)"),
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sound Continuous/Counter"),
              QT_TRANSLATE_NOOP("IOViewer", "Initialization (W)"),
          } },
      { nullptr,
          0x80,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000080-SGCNT0_L"),
          0xFF77,
          {
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Right Volume (3 bits)"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Left Volume (3 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Channel 1->Right"),
              QT_TRANSLATE_NOOP("IOViewer", "Channel 2->Right"),
              QT_TRANSLATE_NOOP("IOViewer", "Channel 3->Right"),
              QT_TRANSLATE_NOOP("IOViewer", "Channel 4->Right"),
              QT_TRANSLATE_NOOP("IOViewer", "Channel 1->Left"),
              QT_TRANSLATE_NOOP("IOViewer", "Channel 2->Left"),
              QT_TRANSLATE_NOOP("IOViewer", "Channel 3->Left"),
              QT_TRANSLATE_NOOP("IOViewer", "Channel 4->Left"),
          } },
      { nullptr,
          0x82,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000082-SGCNT0_H"),
          0xFF0F,
          {
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sound 1-4 Volume (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound A Volume"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound B Volume"),
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound A->Right"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound A->Left"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound A Timer"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound A Reset FIFO"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound B->Right"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound B->Left"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound B Timer"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA Sound B Reset FIFO"),
          } },
      { nullptr,
          0x84,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000084-SGCNT1"),
          0x0080,
          {
              QT_TRANSLATE_NOOP("IOViewer", "Sound 1 On"),
              QT_TRANSLATE_NOOP("IOViewer", "Sound 2 On"),
              QT_TRANSLATE_NOOP("IOViewer", "Sound 3 On"),
              QT_TRANSLATE_NOOP("IOViewer", "Sound 4 On"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Master Sound Enable"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { nullptr,
          0x88,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000088-SGBIAS"),
          0xC3FF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Bias Level (10 bits)"),
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Sampling Rate (2 bits)"),
          } },
      { nullptr,
          0xA0,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000A0-SIGFIFOA_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Data 0 (8 bits)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Data 1 (8 bits)"),
          } },
      { nullptr,
          0xA2,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000A2-SIGFIFOA_H"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Data 2 (8 bits)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Data 3 (8 bits)"),
          } },
      { nullptr,
          0xA4,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000A4-SIGFIFOB_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Data 0 (8 bits)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Data 1 (8 bits)"),
          } },
      { nullptr,
          0xA6,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000A6-SIGFIFOB_H"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Data 2 (8 bits)"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Data 3 (8 bits)"),
          } },
      { &DM0SAD_L,
          0xB0,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000B0-DM0SAD_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address (lower 16 bits)"),
          } },
      { &DM0SAD_H,
          0xB2,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000B2-DM0SAD_H"),
          0x07FF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address (upper 11 bits)"),
              "",
              "",
              "",
              "",
              "",
          } },
      { &DM0DAD_L,
          0xB4,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000B4-DM0DAD_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address (lower 16 bits)"),
          } },
      { &DM0DAD_H,
          0xB6,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000B6-DM0DAD_H"),
          0x07FF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address (upper 11 bits)"),
              "",
              "",
              "",
              "",
              "",
          } },
      { &DM0CNT_L,
          0xB8,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000B8-DM0CNT_L"),
          0x3FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Count (14 bits)"),
              "",
              "",
          } },
      { &DM0CNT_H,
          0xBA,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000BA-DM0CNT_H"),
          0xF7E0,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address Control (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address Control (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Repeat"),
              QT_TRANSLATE_NOOP("IOViewer", "Transfer Type"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Start Timing (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Request"),
              QT_TRANSLATE_NOOP("IOViewer", "Enable"),
          } },
      { &DM1SAD_L,
          0xBC,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000BC-DM1SAD_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address (lower 16 bits)"),
          } },
      { &DM1SAD_H,
          0xBE,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000BE-DM1SAD_H"),
          0x0FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address (upper 12 bits)"),
              "",
              "",
              "",
              "",
          } },
      { &DM1DAD_L,
          0xC0,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000C0-DM1DAD_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address (lower 16 bits)"),
          } },
      { &DM1DAD_H,
          0xC2,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000C2-DM1DAD_H"),
          0x07FF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address (upper 11 bits)"),
              "",
              "",
              "",
              "",
              "",
          } },
      { &DM1CNT_L,
          0xC4,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000C4-DM1CNT_L"),
          0x3FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Count (14 bits)"),
              "",
              "",
          } },
      { &DM1CNT_H,
          0xC6,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000C6-DM1CNT_H"),
          0xF7E0,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address Control (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address Control (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Repeat"),
              QT_TRANSLATE_NOOP("IOViewer", "Transfer Type"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Start Timing (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Request"),
              QT_TRANSLATE_NOOP("IOViewer", "Enable"),
          } },
      { &DM2SAD_L,
          0xC8,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000C8-DM2SAD_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address (lower 16 bits)"),
          } },
      { &DM2SAD_H,
          0xCA,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000CA-DM2SAD_H"),
          0x0FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address (upper 12 bits)"),
              "",
              "",
              "",
              "",
          } },
      { &DM2DAD_L,
          0xCC,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000CC-DM2DAD_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address (lower 16 bits)"),
          } },
      { &DM2DAD_H,
          0xCE,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000CE-DM2DAD_H"),
          0x07FF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address (upper 11 bits)"),
              "",
              "",
              "",
              "",
              "",
          } },
      { &DM2CNT_L,
          0xD0,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000D0-DM2CNT_L"),
          0x3FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Count (14 bits)"),
              "",
              "",
          } },
      { &DM2CNT_H,
          0xD2,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000D2-DM2CNT_H"),
          0xF7E0,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address Control (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address Control (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Repeat"),
              QT_TRANSLATE_NOOP("IOViewer", "Transfer Type"),
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Start Timing (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Request"),
              QT_TRANSLATE_NOOP("IOViewer", "Enable"),
          } },
      { &DM3SAD_L,
          0xD4,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000D4-DM3SAD_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address (lower 16 bits)"),
          } },
      { &DM3SAD_H,
          0xD6,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000D6-DM3SAD_H"),
          0x0FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address (upper 12 bits)"),
              "",
              "",
              "",
              "",
          } },
      { &DM3DAD_L,
          0xD8,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000D8-DM3DAD_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address (lower 16 bits)"),
          } },
      { &DM3DAD_H,
          0xDA,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000DA-DM3DAD_H"),
          0x0FFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address (upper 12 bits)"),
              "",
              "",
              "",
              "",
          } },
      { &DM3CNT_L,
          0xDC,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000DC-DM3CNT_L"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Count (16 bits)"),
          } },
      { &DM3CNT_H,
          0xDE,
          QT_TRANSLATE_NOOP("IOViewer", "0x40000DE-DM3CNT_H"),
          0xFFE0,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Destination Address Control (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Source Address Control (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Repeat"),
              QT_TRANSLATE_NOOP("IOViewer", "Transfer Type"),
              QT_TRANSLATE_NOOP("IOViewer", "Game Pak Data Request"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Start Timing (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Request"),
              QT_TRANSLATE_NOOP("IOViewer", "Enable"),
          } },
      { &TM0D,
          0x100,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000100-TM0D"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Timer Counter (16 bits)"),
          } },
      { &TM0CNT,
          0x102,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000102-TM0CNT"),
          0x00C7,
          {
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Scalar Selection (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Count Up"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Request"),
              QT_TRANSLATE_NOOP("IOViewer", "Enable"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { &TM1D,
          0x104,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000104-TM1D"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Timer Counter (16 bits)"),
          } },
      { &TM1CNT,
          0x106,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000106-TM1CNT"),
          0x00C7,
          {
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Scalar Selection (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Count Up"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Request"),
              QT_TRANSLATE_NOOP("IOViewer", "Enable"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { &TM2D,
          0x108,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000108-TM2D"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Timer Counter (16 bits)"),
          } },
      { &TM2CNT,
          0x10A,
          QT_TRANSLATE_NOOP("IOViewer", "0x400010A-TM2CNT"),
          0x00C7,
          {
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Scalar Selection (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Count Up"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Request"),
              QT_TRANSLATE_NOOP("IOViewer", "Enable"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { &TM3D,
          0x10C,
          QT_TRANSLATE_NOOP("IOViewer", "0x400010C-TM3D"),
          0xFFFF,
          {
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Timer Counter (16 bits)"),
          } },
      { &TM3CNT,
          0x10E,
          QT_TRANSLATE_NOOP("IOViewer", "0x400010E-TM3CNT"),
          0x00C7,
          {
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Scalar Selection (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Count Up"),
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Request"),
              QT_TRANSLATE_NOOP("IOViewer", "Enable"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { &P1,
          0x130,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000130-P1"),
          0x03FF,
          {
              QT_TRANSLATE_NOOP("IOViewer", "A"),
              QT_TRANSLATE_NOOP("IOViewer", "B"),
              QT_TRANSLATE_NOOP("IOViewer", "Select"),
              QT_TRANSLATE_NOOP("IOViewer", "Start"),
              QT_TRANSLATE_NOOP("IOViewer", "Right"),
              QT_TRANSLATE_NOOP("IOViewer", "Left"),
              QT_TRANSLATE_NOOP("IOViewer", "Up"),
              QT_TRANSLATE_NOOP("IOViewer", "Down"),
              QT_TRANSLATE_NOOP("IOViewer", "Shoulder Right"),
              QT_TRANSLATE_NOOP("IOViewer", "Shoulder Left"),
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { nullptr,
          0x132,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000132-P1CNT"),
          0xC3FF,
          {
              QT_TRANSLATE_NOOP("IOViewer", "A"),
              QT_TRANSLATE_NOOP("IOViewer", "B"),
              QT_TRANSLATE_NOOP("IOViewer", "Select"),
              QT_TRANSLATE_NOOP("IOViewer", "Start"),
              QT_TRANSLATE_NOOP("IOViewer", "Right"),
              QT_TRANSLATE_NOOP("IOViewer", "Left"),
              QT_TRANSLATE_NOOP("IOViewer", "Up"),
              QT_TRANSLATE_NOOP("IOViewer", "Down"),
              QT_TRANSLATE_NOOP("IOViewer", "Shoulder Right"),
              QT_TRANSLATE_NOOP("IOViewer", "Shoulder Left"),
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Request"),
              QT_TRANSLATE_NOOP("IOViewer", "Interrupt Condition"),
          } },
      { &IE,
          0x200,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000200-IE"),
          0x3FFF,
          {
              QT_TRANSLATE_NOOP("IOViewer", "VBlank"),
              QT_TRANSLATE_NOOP("IOViewer", "HBlank"),
              QT_TRANSLATE_NOOP("IOViewer", "VCount"),
              QT_TRANSLATE_NOOP("IOViewer", "Timer 0"),
              QT_TRANSLATE_NOOP("IOViewer", "Timer 1"),
              QT_TRANSLATE_NOOP("IOViewer", "Timer 2"),
              QT_TRANSLATE_NOOP("IOViewer", "Timer 3"),
              QT_TRANSLATE_NOOP("IOViewer", "Serial"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA 0"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA 1"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA 2"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA 3"),
              QT_TRANSLATE_NOOP("IOViewer", "Keypad"),
              QT_TRANSLATE_NOOP("IOViewer", "Game Pak"),
              "",
              "",
          } },
      { &IF,
          0x202,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000202-IF"),
          0x0000,
          {
              QT_TRANSLATE_NOOP("IOViewer", "VBlank"),
              QT_TRANSLATE_NOOP("IOViewer", "HBlank"),
              QT_TRANSLATE_NOOP("IOViewer", "VCount"),
              QT_TRANSLATE_NOOP("IOViewer", "Timer 0"),
              QT_TRANSLATE_NOOP("IOViewer", "Timer 1"),
              QT_TRANSLATE_NOOP("IOViewer", "Timer 2"),
              QT_TRANSLATE_NOOP("IOViewer", "Timer 3"),
              QT_TRANSLATE_NOOP("IOViewer", "Serial"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA 0"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA 1"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA 2"),
              QT_TRANSLATE_NOOP("IOViewer", "DMA 3"),
              QT_TRANSLATE_NOOP("IOViewer", "Keypad"),
              QT_TRANSLATE_NOOP("IOViewer", "Game Pak"),
              "",
              "",
          } },
      { nullptr,
          0x204,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000204-WAITCNT"),
          0x5FFF,
          {
              "",
              QT_TRANSLATE_NOOP("IOViewer", "SRAM Wait Control (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Wait State 0 First Access (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Wait State 0 Second Access"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Wait State 1 First Access (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Wait State 1 Second Access"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Wait State 2 First Access (2 bits)"),
              QT_TRANSLATE_NOOP("IOViewer", "Wait State 2 Second Access"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "PHI Terminal Output (2 bits)"),
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Game Pak Prefetch Buffer"),
              QT_TRANSLATE_NOOP("IOViewer", "Game Pak Type Flag"),
          } },
      { &IME,
          0x208,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000208-IME"),
          0x0001,
          {
              QT_TRANSLATE_NOOP("IOViewer", "Master Interrupt Enable"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
          } },
      { nullptr,
          0x300,
          QT_TRANSLATE_NOOP("IOViewer", "0x4000300-HALTCNT"),
          0x8001,
          {
              QT_TRANSLATE_NOOP("IOViewer", "First Boot"),
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              "",
              QT_TRANSLATE_NOOP("IOViewer", "Power Down"),
          } },
    };

#define NUM_IOREGS (sizeof(ioregs) / sizeof(ioregs[0]))
