name: visualboyadvance-m
version: 2.1.0
summary: Nintendo Game Boy Advance Emulator
description: |
  An open-source Nintendo Game Boy, Super Game Boy, Game Boy Advance Emulators.

confinement: devmode

parts:
  vbam:
    source: https://github.com/visualboyadvance-m/visualboyadvance-m/archive/v2.1.0.tar.gz
    plugin: cmake
    build-packages:
      - g++
      - gcc
      - make
      - cmake
      - libwxgtk3.0-gtk3-dev
      - libsdl2-dev
      - libsfml-dev
      - libgtk-3-dev
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/

apps:
  visualboyadvance-m:
    command: visualboyadvance-m
