#!/bin/sh

set -e

LANG=C LC_COLLATE=C LC_CTYPE=C LC_MESSAGES=C LC_MONETARY=C LC_NUMERIC=C LC_TIME=C LC_ALL=C
export LANG LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME LC_ALL

export BUILD_ROOT="$HOME/vbam-build-unix"

. "$(dirname "$0")/../builder/core.sh"

table_line_append DIST_ARGS glib -Dlibmount=false

builder "$@"
