// Command table for the Qt frontend. Generated from src/wx/cmdevents.cpp at
// port time (names, helper strings and enable masks); edit by hand from here on.
#include "qt/config/cmdtab.h"

#include <algorithm>

std::vector<cmditem> cmdtab = {
    {QStringLiteral("OPEN"), "Open ROM...", cmd::kOpen, 0, nullptr},
    {QStringLiteral("OpenGB"), "Open GB...", cmd::kOpenGB, 0, nullptr},
    {QStringLiteral("OpenGBC"), "Open GBC...", cmd::kOpenGBC, 0, nullptr},
    {QStringLiteral("RecentReset"), "Reset recent ROM list", cmd::kRecentReset, 0, nullptr},
    {QStringLiteral("RecentFreeze"), "Freeze recent ROM list (toggle)", cmd::kRecentFreeze, 0, nullptr},
    {QStringLiteral("FILE1"), "Load recent ROM 1", cmd::kFile1, 0, nullptr},
    {QStringLiteral("FILE2"), "Load recent ROM 2", cmd::kFile2, 0, nullptr},
    {QStringLiteral("FILE3"), "Load recent ROM 3", cmd::kFile3, 0, nullptr},
    {QStringLiteral("FILE4"), "Load recent ROM 4", cmd::kFile4, 0, nullptr},
    {QStringLiteral("FILE5"), "Load recent ROM 5", cmd::kFile5, 0, nullptr},
    {QStringLiteral("FILE6"), "Load recent ROM 6", cmd::kFile6, 0, nullptr},
    {QStringLiteral("FILE7"), "Load recent ROM 7", cmd::kFile7, 0, nullptr},
    {QStringLiteral("FILE8"), "Load recent ROM 8", cmd::kFile8, 0, nullptr},
    {QStringLiteral("FILE9"), "Load recent ROM 9", cmd::kFile9, 0, nullptr},
    {QStringLiteral("FILE10"), "Load recent ROM 10", cmd::kFile10, 0, nullptr},
    {QStringLiteral("RomInformation"), "ROM information...", cmd::kRomInformation, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("ResetLoadingDotCodeFile"), "Reset Loading e-Reader Dot Code", cmd::kResetLoadingDotCodeFile, CMDEN_GBA, nullptr},
    {QStringLiteral("SetLoadingDotCodeFile"), "Load e-Reader Dot Code...", cmd::kSetLoadingDotCodeFile, CMDEN_GBA, nullptr},
    {QStringLiteral("ResetSavingDotCodeFile"), "Reset Saving e-Reader Dot Code", cmd::kResetSavingDotCodeFile, CMDEN_GBA, nullptr},
    {QStringLiteral("SetSavingDotCodeFile"), "Save e-Reader Dot Code...", cmd::kSetSavingDotCodeFile, CMDEN_GBA, nullptr},
    {QStringLiteral("ImportBatteryFile"), "Import battery file...", cmd::kImportBatteryFile, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("ImportGamesharkCodeFile"), "Import Game Shark code file...", cmd::kImportGamesharkCodeFile, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("ImportGamesharkActionReplaySnapshot"), "Import Game Shark Action Replay snapshot...", cmd::kImportGamesharkActionReplaySnapshot, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("ExportBatteryFile"), "Export battery file...", cmd::kExportBatteryFile, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("ExportGamesharkSnapshot"), "Export GameShark snapshot...", cmd::kExportGamesharkSnapshot, CMDEN_GBA, nullptr},
    {QStringLiteral("ScreenCapture"), "Screen capture...", cmd::kScreenCapture, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("RecordSoundStartRecording"), "Start sound recording...", cmd::kRecordSoundStartRecording, CMDEN_NSREC, nullptr},
    {QStringLiteral("RecordSoundStopRecording"), "Stop sound recording", cmd::kRecordSoundStopRecording, CMDEN_SREC, nullptr},
    {QStringLiteral("RecordAVIStartRecording"), "Start video recording...", cmd::kRecordAVIStartRecording, CMDEN_NVREC, nullptr},
    {QStringLiteral("RecordAVIStopRecording"), "Stop video recording", cmd::kRecordAVIStopRecording, CMDEN_VREC, nullptr},
    {QStringLiteral("RecordMovieStartRecording"), "Start game recording...", cmd::kRecordMovieStartRecording, CMDEN_NGREC, nullptr},
    {QStringLiteral("RecordMovieStopRecording"), "Stop game recording", cmd::kRecordMovieStopRecording, CMDEN_GREC, nullptr},
    {QStringLiteral("PlayMovieStartPlaying"), "Start playing movie...", cmd::kPlayMovieStartPlaying, CMDEN_NGREC | CMDEN_NGPLAY, nullptr},
    {QStringLiteral("PlayMovieStopPlaying"), "Stop playing movie", cmd::kPlayMovieStopPlaying, CMDEN_GPLAY, nullptr},
    {QStringLiteral("CLOSE"), "Close", cmd::kClose, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("EXIT"), "Exit", cmd::kExit, 0, nullptr},
    {QStringLiteral("Pause"), "Pause (toggle)", cmd::kPause, 0, nullptr},
    {QStringLiteral("EmulatorSpeedupToggle"), "Turbo mode (toggle)", cmd::kEmulatorSpeedupToggle, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("Reset"), "Reset", cmd::kReset, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("ToggleFullscreen"), "Full screen (toggle)", cmd::kToggleFullscreen, 0, nullptr},
    {QStringLiteral("JoypadAutofireA"), "Autofire A (toggle)", cmd::kJoypadAutofireA, 0, nullptr},
    {QStringLiteral("JoypadAutofireB"), "Autofire B (toggle)", cmd::kJoypadAutofireB, 0, nullptr},
    {QStringLiteral("JoypadAutofireL"), "Autofire L (toggle)", cmd::kJoypadAutofireL, 0, nullptr},
    {QStringLiteral("JoypadAutofireR"), "Autofire R (toggle)", cmd::kJoypadAutofireR, 0, nullptr},
    {QStringLiteral("JoypadAutoholdUp"), "Autohold Up (toggle)", cmd::kJoypadAutoholdUp, 0, nullptr},
    {QStringLiteral("JoypadAutoholdDown"), "Autohold Down (toggle)", cmd::kJoypadAutoholdDown, 0, nullptr},
    {QStringLiteral("JoypadAutoholdLeft"), "Autohold Left (toggle)", cmd::kJoypadAutoholdLeft, 0, nullptr},
    {QStringLiteral("JoypadAutoholdRight"), "Autohold Right (toggle)", cmd::kJoypadAutoholdRight, 0, nullptr},
    {QStringLiteral("JoypadAutoholdA"), "Autohold A (toggle)", cmd::kJoypadAutoholdA, 0, nullptr},
    {QStringLiteral("JoypadAutoholdB"), "Autohold B (toggle)", cmd::kJoypadAutoholdB, 0, nullptr},
    {QStringLiteral("JoypadAutoholdL"), "Autohold L (toggle)", cmd::kJoypadAutoholdL, 0, nullptr},
    {QStringLiteral("JoypadAutoholdR"), "Autohold R (toggle)", cmd::kJoypadAutoholdR, 0, nullptr},
    {QStringLiteral("JoypadAutoholdSelect"), "Autohold Select (toggle)", cmd::kJoypadAutoholdSelect, 0, nullptr},
    {QStringLiteral("JoypadAutoholdStart"), "Autohold Start (toggle)", cmd::kJoypadAutoholdStart, 0, nullptr},
    {QStringLiteral("AllowKeyboardBackgroundInput"), "Allow keyboard background input (toggle)", cmd::kAllowKeyboardBackgroundInput, 0, nullptr},
    {QStringLiteral("AllowJoystickBackgroundInput"), "Allow joystick background input (toggle)", cmd::kAllowJoystickBackgroundInput, 0, nullptr},
    {QStringLiteral("LoadGameRecent"), "Load most recent save", cmd::kLoadGameRecent, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGameAutoLoad"), "Auto load most recent save (toggle)", cmd::kLoadGameAutoLoad, 0, nullptr},
    {QStringLiteral("LoadGame01"), "Load saved state 1", cmd::kLoadGame01, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGame02"), "Load saved state 2", cmd::kLoadGame02, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGame03"), "Load saved state 3", cmd::kLoadGame03, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGame04"), "Load saved state 4", cmd::kLoadGame04, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGame05"), "Load saved state 5", cmd::kLoadGame05, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGame06"), "Load saved state 6", cmd::kLoadGame06, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGame07"), "Load saved state 7", cmd::kLoadGame07, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGame08"), "Load saved state 8", cmd::kLoadGame08, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGame09"), "Load saved state 9", cmd::kLoadGame09, CMDEN_SAVST, nullptr},
    {QStringLiteral("LoadGame10"), "Load saved state 10", cmd::kLoadGame10, CMDEN_SAVST, nullptr},
    {QStringLiteral("Load"), "Load state...", cmd::kLoad, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("KeepSaves"), "Do not load battery saves (toggle)", cmd::kKeepSaves, 0, nullptr},
    {QStringLiteral("KeepCheats"), "Do not change cheat list (toggle)", cmd::kKeepCheats, 0, nullptr},
    {QStringLiteral("SaveGameOldest"), "Save state to oldest slot", cmd::kSaveGameOldest, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame01"), "Save state 1", cmd::kSaveGame01, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame02"), "Save state 2", cmd::kSaveGame02, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame03"), "Save state 3", cmd::kSaveGame03, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame04"), "Save state 4", cmd::kSaveGame04, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame05"), "Save state 5", cmd::kSaveGame05, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame06"), "Save state 6", cmd::kSaveGame06, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame07"), "Save state 7", cmd::kSaveGame07, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame08"), "Save state 8", cmd::kSaveGame08, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame09"), "Save state 9", cmd::kSaveGame09, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGame10"), "Save state 10", cmd::kSaveGame10, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("Save"), "Save state as...", cmd::kSave, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("LoadGameSlot"), "Load current state slot", cmd::kLoadGameSlot, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SaveGameSlot"), "Save current state slot", cmd::kSaveGameSlot, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("IncrGameSlot"), "Increase state slot number", cmd::kIncrGameSlot, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("DecrGameSlot"), "Decrease state slot number", cmd::kDecrGameSlot, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("IncrGameSlotSave"), "Increase state slot number and save", cmd::kIncrGameSlotSave, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("Rewind"), "Rewind", cmd::kRewind, CMDEN_REWIND, nullptr},
    {QStringLiteral("CheatsList"), "List cheats...", cmd::kCheatsList, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("CheatsSearch"), "Create cheat...", cmd::kCheatsSearch, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("CheatsAutoSaveLoad"), "Auto save/load cheats (toggle)", cmd::kCheatsAutoSaveLoad, 0, nullptr},
    {QStringLiteral("CheatsEnable"), "Enable cheats (toggle)", cmd::kCheatsEnable, 0, nullptr},
    {QStringLiteral("ColorizerHack"), "Enable Colorizer Hack (toggle)", cmd::kColorizerHack, 0, nullptr},
    {QStringLiteral("VideoLayersBG0"), "Video layer BG0 (toggle)", cmd::kVideoLayersBG0, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("VideoLayersBG1"), "Video layer BG1 (toggle)", cmd::kVideoLayersBG1, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("VideoLayersBG2"), "Video layer BG2 (toggle)", cmd::kVideoLayersBG2, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("VideoLayersBG3"), "Video layer BG3 (toggle)", cmd::kVideoLayersBG3, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("VideoLayersOBJ"), "Video layer OBJ (toggle)", cmd::kVideoLayersOBJ, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("VideoLayersWIN0"), "Video layer WIN0 (toggle)", cmd::kVideoLayersWIN0, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("VideoLayersWIN1"), "Video layer WIN1 (toggle)", cmd::kVideoLayersWIN1, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("VideoLayersOBJWIN"), "Video layer OBJWIN (toggle)", cmd::kVideoLayersOBJWIN, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("VideoLayersReset"), "Show all video layers", cmd::kVideoLayersReset, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SoundChannel1"), "Sound Channel 1 (toggle)", cmd::kSoundChannel1, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SoundChannel2"), "Sound Channel 2 (toggle)", cmd::kSoundChannel2, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SoundChannel3"), "Sound Channel 3 (toggle)", cmd::kSoundChannel3, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("SoundChannel4"), "Sound Channel 4 (toggle)", cmd::kSoundChannel4, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("DirectSoundA"), "Direct Sound A (toggle)", cmd::kDirectSoundA, CMDEN_GBA, nullptr},
    {QStringLiteral("DirectSoundB"), "Direct Sound B (toggle)", cmd::kDirectSoundB, CMDEN_GBA, nullptr},
    {QStringLiteral("ToggleSound"), "Enable/disable all sound channels", cmd::kToggleSound, 0, nullptr},
    {QStringLiteral("IncreaseVolume"), "Increase volume", cmd::kIncreaseVolume, 0, nullptr},
    {QStringLiteral("DecreaseVolume"), "Decrease volume", cmd::kDecreaseVolume, 0, nullptr},
    {QStringLiteral("NextFrame"), "Next Frame", cmd::kNextFrame, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("Disassemble"), "Disassemble...", cmd::kDisassemble, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("Logging"), "Logging...", cmd::kLogging, 0, nullptr},
    {QStringLiteral("IOViewer"), "I/O Viewer...", cmd::kIOViewer, CMDEN_GBA, nullptr},
    {QStringLiteral("MapViewer"), "Map Viewer...", cmd::kMapViewer, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("MemoryViewer"), "Memory Viewer...", cmd::kMemoryViewer, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("OAMViewer"), "OAM Viewer...", cmd::kOAMViewer, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("PaletteViewer"), "Palette Viewer...", cmd::kPaletteViewer, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("TileViewer"), "Tile Viewer...", cmd::kTileViewer, CMDEN_GB | CMDEN_GBA, nullptr},
    {QStringLiteral("LuaRunScript"), "Run Lua script...", cmd::kLuaRunScript, 0, nullptr},
    {QStringLiteral("LuaStopScript"), "Stop Lua script", cmd::kLuaStopScript, 0, nullptr},
    {QStringLiteral("LuaConsole"), "Show Lua console", cmd::kLuaConsole, 0, nullptr},
    {QStringLiteral("LuaEditor"), "Show Lua editor", cmd::kLuaEditor, 0, nullptr},
    {QStringLiteral("DebugGDBPort"), "Configure port...", cmd::kDebugGDBPort, 0, nullptr},
    {QStringLiteral("DebugGDBBreakOnLoad"), "Break on load", cmd::kDebugGDBBreakOnLoad, 0, nullptr},
    {QStringLiteral("DebugGDBBreak"), "Break into GDB", cmd::kDebugGDBBreak, CMDEN_NGDB_GBA | CMDEN_GDB, nullptr},
    {QStringLiteral("DebugGDBDisconnect"), "Disconnect GDB", cmd::kDebugGDBDisconnect, CMDEN_GDB, nullptr},
    {QStringLiteral("GeneralConfigure"), "General options...", cmd::kGeneralConfigure, 0, nullptr},
    {QStringLiteral("SpeedupConfigure"), "Speedup / Turbo options...", cmd::kSpeedupConfigure, 0, nullptr},
    {QStringLiteral("GameBoyConfigure"), "Game Boy options...", cmd::kGameBoyConfigure, 0, nullptr},
    {QStringLiteral("SetSize1x"), "1x", cmd::kSetSize1x, 0, nullptr},
    {QStringLiteral("SetSize2x"), "2x", cmd::kSetSize2x, 0, nullptr},
    {QStringLiteral("SetSize3x"), "3x", cmd::kSetSize3x, 0, nullptr},
    {QStringLiteral("SetSize4x"), "4x", cmd::kSetSize4x, 0, nullptr},
    {QStringLiteral("SetSize5x"), "5x", cmd::kSetSize5x, 0, nullptr},
    {QStringLiteral("SetSize6x"), "6x", cmd::kSetSize6x, 0, nullptr},
    {QStringLiteral("GameBoyAdvanceConfigure"), "Game Boy Advance options...", cmd::kGameBoyAdvanceConfigure, 0, nullptr},
    {QStringLiteral("DisplayConfigure"), "Display options...", cmd::kDisplayConfigure, CMDEN_NREC_ANY, nullptr},
    {QStringLiteral("ChangeFilter"), "Change Pixel Filter", cmd::kChangeFilter, CMDEN_NREC_ANY, nullptr},
    {QStringLiteral("ChangeIFB"), "Change Interframe Blending", cmd::kChangeIFB, CMDEN_NREC_ANY, nullptr},
    {QStringLiteral("SoundConfigure"), "Sound options...", cmd::kSoundConfigure, CMDEN_NREC_ANY, nullptr},
    {QStringLiteral("EmulatorDirectories"), "Directories...", cmd::kEmulatorDirectories, 0, nullptr},
    {QStringLiteral("JoypadConfigure"), "Joypad options...", cmd::kJoypadConfigure, 0, nullptr},
    {QStringLiteral("Customize"), "Customize UI...", cmd::kCustomize, 0, nullptr},
    {QStringLiteral("UpdateEmu"), "Check for updates...", cmd::kUpdateEmu, 0, nullptr},
    {QStringLiteral("FactoryReset"), "Factory Reset...", cmd::kFactoryReset, 0, nullptr},
    {QStringLiteral("BugReport"), "Report bugs...", cmd::kBugReport, 0, nullptr},
    {QStringLiteral("FAQ"), "VBA-M support forum", cmd::kFaq, 0, nullptr},
    {QStringLiteral("Translate"), "Translations", cmd::kTranslate, 0, nullptr},
    {QStringLiteral("ABOUT"), "About...", cmd::kAbout, 0, nullptr},
    {QStringLiteral("Bilinear"), "Use bilinear filter with 3d renderer", cmd::kBilinear, 0, nullptr},
    {QStringLiteral("RetainAspect"), "Retain aspect ratio when resizing", cmd::kRetainAspect, 0, nullptr},
    {QStringLiteral("Printer"), "Enable printer emulation", cmd::kPrinter, CMDEN_LINK_OFF, nullptr},
    {QStringLiteral("PrintGather"), "Automatically gather a full page before printing", cmd::kPrintGather, 0, nullptr},
    {QStringLiteral("PrintSnap"), "Automatically save printouts as screen captures with -print suffix", cmd::kPrintSnap, 0, nullptr},
    {QStringLiteral("GBASoundInterpolation"), "GBA sound interpolation", cmd::kGBASoundInterpolation, 0, nullptr},
    {QStringLiteral("GBDeclicking"), "GB sound declicking", cmd::kGBDeclicking, 0, nullptr},
    {QStringLiteral("GBEnhanceSound"), "Enable GB sound effects", cmd::kGBEnhanceSound, 0, nullptr},
    {QStringLiteral("GBSurround"), "GB surround sound effect (%)", cmd::kGBSurround, 0, nullptr},
    {QStringLiteral("AGBPrinter"), "Enable AGB printer", cmd::kAGBPrinter, 0, nullptr},
    {QStringLiteral("GBALcdFilter"), "Enable LCD filter", cmd::kGBALcdFilter, CMDEN_GBA, nullptr},
    {QStringLiteral("GBLcdFilter"), "Enable LCD filter", cmd::kGBLcdFilter, CMDEN_GB, nullptr},
    {QStringLiteral("ApplyPatches"), "Apply IPS/UPS/IPF patches if found", cmd::kApplyPatches, 0, nullptr},
    {QStringLiteral("KeepOnTop"), "Keep window on top", cmd::kKeepOnTop, 0, nullptr},
    {QStringLiteral("StatusBar"), "Enable status bar", cmd::kStatusBar, 0, nullptr},
    {QStringLiteral("NoStatusMsg"), "Disable on-screen status messages", cmd::kNoStatusMsg, 0, nullptr},
    {QStringLiteral("BitDepth"), "Bit depth", cmd::kBitDepth, 0, nullptr},
    {QStringLiteral("FrameSkipAuto"), "Auto Skip frames.", cmd::kFrameSkipAuto, 0, nullptr},
    {QStringLiteral("Fullscreen"), "Enter fullscreen mode at startup", cmd::kFullscreen, 0, nullptr},
    {QStringLiteral("PauseWhenInactive"), "Pause game when main window loses focus", cmd::kPauseWhenInactive, 0, nullptr},
    {QStringLiteral("RTC"), "Enable RTC (vba-over.ini override is rtcEnabled", cmd::kRtc, 0, nullptr},
    {QStringLiteral("SkipIntro"), "Skip BIOS initialization", cmd::kSkipIntro, 0, nullptr},
    {QStringLiteral("BootRomEn"), "Use the specified BIOS file for GBA", cmd::kBootRomEn, 0, nullptr},
    {QStringLiteral("BootRomGB"), "Use the specified BIOS file for GB", cmd::kBootRomGB, 0, nullptr},
    {QStringLiteral("BootRomGBC"), "Use the specified BIOS file for GBC", cmd::kBootRomGBC, 0, nullptr},
    {QStringLiteral("VSync"), "Wait for vertical sync", cmd::kVSync, 0, nullptr},
    {QStringLiteral("HideMenuBar"), "Hide menu bar when mouse is inactive", cmd::kHideMenuBar, 0, nullptr},
    {QStringLiteral("OnScreenController"), "Show the on-screen touch controller", cmd::kOnScreenController, 0, nullptr},
    {QStringLiteral("SuspendScreenSaver"), "Suspend screensaver when game is running", cmd::kSuspendScreenSaver, 0, nullptr},
    {QStringLiteral("LanLink"), "Start link", cmd::kLanLink, CMDEN_LINK_ANY, nullptr},
    {QStringLiteral("LinkType0Nothing"), "Link nothing", cmd::kLinkType0Nothing, 0, nullptr},
    {QStringLiteral("LinkType1Cable"), "Link cable", cmd::kLinkType1Cable, 0, nullptr},
    {QStringLiteral("LinkType2Wireless"), "Link wireless", cmd::kLinkType2Wireless, 0, nullptr},
    {QStringLiteral("LinkType3GameCube"), "Link GameCube", cmd::kLinkType3GameCube, 0, nullptr},
    {QStringLiteral("LinkType4Gameboy"), "Link Gameboy", cmd::kLinkType4Gameboy, 0, nullptr},
    {QStringLiteral("LinkAuto"), "Enable link at boot", cmd::kLinkAuto, 0, nullptr},
    {QStringLiteral("SpeedOn"), "Enable faster network protocol by default", cmd::kSpeedOn, 0, nullptr},
    {QStringLiteral("LinkProto"), "Local host IPC", cmd::kLinkProto, 0, nullptr},
    {QStringLiteral("LinkConfigure"), "Link options...", cmd::kLinkConfigure, 0, nullptr},
    {QStringLiteral("ExternalTranslations"), "Use external translations", cmd::kExternalTranslations, 0, nullptr},
    {QStringLiteral("Language0"), "Default Language", cmd::kLanguage0, 0, nullptr},
    {QStringLiteral("Language1"), "Spanish (Latin American)", cmd::kLanguage1, 0, nullptr},
    {QStringLiteral("Language2"), "Spanish", cmd::kLanguage2, 0, nullptr},
    {QStringLiteral("Language3"), "French (France)", cmd::kLanguage3, 0, nullptr},
    {QStringLiteral("Language4"), "Hebrew (Israel)", cmd::kLanguage4, 0, nullptr},
    {QStringLiteral("Language5"), "Hungarian (Hungary)", cmd::kLanguage5, 0, nullptr},
    {QStringLiteral("Language6"), "Indonesian", cmd::kLanguage6, 0, nullptr},
    {QStringLiteral("Language7"), "Italian", cmd::kLanguage7, 0, nullptr},
    {QStringLiteral("Language8"), "Korean (Korea)", cmd::kLanguage8, 0, nullptr},
    {QStringLiteral("Language9"), "Polish (Poland)", cmd::kLanguage9, 0, nullptr},
    {QStringLiteral("Language10"), "Portuguese (Brazil)", cmd::kLanguage10, 0, nullptr},
    {QStringLiteral("Language11"), "Swedish", cmd::kLanguage11, 0, nullptr},
    {QStringLiteral("Language12"), "Turkish", cmd::kLanguage12, 0, nullptr},
    {QStringLiteral("Language13"), "Ukrainian", cmd::kLanguage13, 0, nullptr},
    {QStringLiteral("Language14"), "Chinese (China)", cmd::kLanguage14, 0, nullptr},
    {QStringLiteral("NOOP"), "Do nothing", cmd::kNoop, CMDEN_NEVER, nullptr},
};
