name: MSYS2
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        build_type: [release, debug]
        build_options: [default, link_off, translations_only]
        include:
          - cmake_build: '-DCMAKE_BUILD_TYPE=Release'
            build_type: release
          - cmake_build: '-DCMAKE_BUILD_TYPE=Debug'
            build_type: debug
          - cmake_options: '-DENABLE_SDL=ON -DENABLE_LIBRETRO=ON'
            build_options: default
          - cmake_options: '-DENABLE_LINK=OFF -DENABLE_SDL=ON -DENABLE_LIBRETRO=ON'
            build_options: link_off
          - cmake_options: '-DTRANSLATIONS_ONLY=ON'
            build_options: translations_only
        exclude:
          # Exclude debug/translations_only build
          - build_type: debug
            build_options: translations_only
    runs-on: windows-latest
    env:
      MSYSTEM: CLANG64
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with: 
          submodules: recursive
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
      - name: Install deps
        run: >-
          bash installdeps

      # CMake build
      - name: Configure CMake
        run: cmake -B build -G Ninja ${{ matrix.cmake_build }} -DENABLE_LTO=OFF ${{ matrix.cmake_options }}
      - name: Build
        run: ninja -C build
      - name: Install
        run: ninja -C build install
